### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by tasnimchy96** [andrianarivo/awesome_books#4]
Hi @andrianarivo  , good job so far on the Portfolio project. Below are some ideas and suggestions about the project, cheers! 👍🏽

HIGHLIGHTS 🎯

The project is well structured and organised into folders/directories ✅
The project has a comprehensive README documentation ✅
The project has been deployed properly and is accessible viewed via the demo link provided ✅
The project is very readable and easy to maintain due to the descriptive comments in your files 🥇

**Comment by mohammadamin-alizadeh** [comment]
thank you for your suggestion
